config/routes.rb
Ifbooks::Application.routes.draw do

  get 'admin' => 'admin#index'

  controller :if_sessions do
    get     'group_login' => :new
    post    'group_login' => :create
    delete  'group_logout' => :destroy
  end

  get "admin/index"

  get "if_sessions/new"

  get "if_sessions/create"

  get "if_sessions/destroy"

  resources :ifgroups

  match "register" => 'ifgroups#register'
  resources :members

  mount Refinery::Core::Engine, :at => '/'

  resources :books

end

app/models/ifgroup.rb
class Ifgroup < ActiveRecord::Base

  self.table_name = 'refinery_ifgroups'

  #has_many :subscriptions, :dependent => :destroy
  belongs_to :book, :class_name => '::Book'
  has_many :members, :class_name => '::Member', :dependent => :destroy
  accepts_nested_attributes_for :members
  #accepts_nested_attributes_for :books



  attr_accessible :group_name, :password, :password_confirmation, :title, :first_name, :last_name, :school_name, :address1, :address2, :address3, :town, :county, :post_code, :teacher_email, :group1_email, :group2_email, :invoice_to, :position, :members_attributes, :book_id #, :books_attributes
  acts_as_indexed :fields => [:group_name, :school_name, :address1, :address2, :address3, :town, :county, :post_code, :teacher_email, :group1_email, :group2_email, :invoice_to]

  validates :group_name, :presence => true, :uniqueness => true
  validates :school_name, :presence => true
  has_secure_password


end

app/models/refinery/ifgroups/ifgroup.rb
module Refinery
  module Ifgroups
    class Ifgroup < Refinery::Core::BaseModel
      self.table_name = 'refinery_ifgroups'
      #
      #has_many :subscriptions
      #has_many :books, :through => :subscriptions

      #has_many :subscriptions, :class_name => '::Refinery::Subscriptions::Subscription'
      #has_many :books, :class_name => '::Refinery::Books::Book', :through => :subscriptions


      #has_many :memberships
      #has_many :books, :class_name => '::Refinery::Books::Book', :through => :memberships, :source => :groupable, :source_type => 'Book'
      #has_many :members, :class_name => '::Refinery::Members::Member', :through => :memberships, :source => :groupable, :source_type => 'Member'


      attr_accessible :group_name, :password, :password_confirmation, :title, :first_name, :last_name, :school_name, :address1, :address2, :address3, :town, :county, :post_code, :teacher_email, :group1_email, :group2_email, :invoice_to, :position
      acts_as_indexed :fields => [:group_name, :school_name, :address1, :address2, :address3, :town, :county, :post_code, :teacher_email, :group1_email, :group2_email, :invoice_to]

      validates :group_name, :presence => true, :uniqueness => true
      validates :school_name, :presence => true
      has_secure_password
              
    end
  end
end

app/controllers/ifgroups_controller.rb
class IfgroupsController < ApplicationController

  before_filter :authorize, :find_all_books, :find_page, :find_all_ifgroups
  skip_before_filter :authorize, only: [:register, :new, :create]

  def index

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ifgroups }
    end
  end

  def show
    @ifgroup = Ifgroup.find(params[:id])
    @book = @ifgroup.book
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ifgroup }
    end
  end

  # GET /ifgroups/new
  # GET /ifgroups/new.json
  def new
    @ifgroup = Ifgroup.new
    @book = @books.find(params[:id])
    MyLog.debug "ifgroup id = "
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ifgroup }
    end
  end

  def register
    @members = ::Refinery::Members::Member.order('position ASC')
    @book = @books.find(params[:id])
    new
  end

  # GET /ifgroups/1/edit
  def edit
    @ifgroup = Ifgroup.find(params[:id])
    @book = @ifgroup.book
  end

  # POST /ifgroups
  # POST /ifgroups.json
  def create
    @ifgroup = Ifgroup.new(params[:ifgroup])
    #@book = @books.find(params[:id])
    respond_to do |format|
      if @ifgroup.save
        MyLog.debug "SAVED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        format.html { redirect_to '/welcome', notice: "Ifgroup, #{@ifgroup.group_name}, was successfully created." }
        format.json { render json: @ifgroup, status: :created, location: @ifgroup }
      else
        #format.html { render action: "register"}
        format.html {redirect_to main_app.register_path(:id => @ifgroup.book_id), notice: 'ooops!'}
        format.json { render json: @ifgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ifgroups/1
  # PUT /ifgroups/1.json
  def update
    @ifgroup = Ifgroup.find(params[:id])

    respond_to do |format|
      if @ifgroup.update_attributes(params[:ifgroup])
        format.html { redirect_to @ifgroup, notice: "Ifgroup, #{@ifgroup.group_name}, was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ifgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ifgroup = Ifgroup.find(params[:id])
    @ifgroup.destroy

    respond_to do |format|
      format.html { redirect_to ifgroups_url }
      format.json { head :no_content }
    end
  end

  protected

  def find_page
    @page = ::Refinery::Page.where(:link_url => "/ifgroups").first
  end

end

app/controllers/refinery/ifgroups/Xifgroups_controller.rb
module Refinery
  module Ifgroups
    class IfgroupsController < ::ApplicationController

      before_filter :find_all_ifgroups
      before_filter :find_all_books
      before_filter :find_page

      def index
        # you can use meta fields from your model instead (e.g. browser_title)
        # by swapping @page for @ifgroup in the line below:
        present(@page)
      end

      def show
        @ifgroup = Ifgroup.find(params[:id])

        # you can use meta fields from your model instead (e.g. browser_title)
        # by swapping @page for @ifgroup in the line below:
        present(@page)
      end

    protected

      def find_all_books
        @books = ::Refinery::Books::Book.order('position ASC')
      end

      def find_all_ifgroups
        @ifgroups = Ifgroup.order('position ASC')
      end

      def find_page
        @page = ::Refinery::Page.where(:link_url => "/ifgroups").first
      end

    end
  end
end

app/controllers/refinery/ifgroups/ifgroups_controller.rb
module Refinery
  module Ifgroups
    class IfgroupsController < ::ApplicationController

      before_filter :find_all_ifgroups
      before_filter :find_all_books
      before_filter :find_page

      def index
        # you can use meta fields from your model instead (e.g. browser_title)
        # by swapping @page for @ifgroup in the line below:
        present(@page)
      end

      def show
        @ifgroup = Ifgroup.find(params[:id])

        # you can use meta fields from your model instead (e.g. browser_title)
        # by swapping @page for @ifgroup in the line below:
        present(@page)
      end

    protected

      def find_all_books
        @books = ::Refinery::Books::Book.order('position ASC')
      end

      def find_all_ifgroups
        @ifgroups = Ifgroup.order('position ASC')
      end

      def find_page
        @page = ::Refinery::Page.where(:link_url => "/ifgroups").first
      end

    end
  end
end

app/helpers/ifgroups_helper.rb
module IfgroupsHelper
end

app/views/ifgroups/OLD_form.html.erb
<%= form_for(@ifgroup) do |f| %>
  <% if @ifgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ifgroup.errors.count, "error") %> prohibited this ifgroup from being saved:</h2>

      <ul>
      <% @ifgroup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p id="notice"><%= notice %></p>
  Hello!!!
  <%= f.fields_for :books do |ff| %>
    <p><%= ff.text_field :title %></p>
    <p><%#= ff.link_to_add "Add a question", :subscriptions %></p>
    <p><%#= ff.submit "Submit" %></p>
  <% end %>
  <fieldset>
    <legend>Enter Group details:</legend>
    <div>
      <%= f.label :group_name %><br />
      <%= f.text_field :group_name, size: 30 %>
    </div>
    <div>
      <%= f.label :password, 'Password' %><br />
      <%= f.password_field :password, size: 30 %>
    </div>
    <div>
      <%= f.label :password_confirmation, 'Confirm Password' %><br />
      <%= f.password_field :password_confirmation, size: 30 %>
    </div>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :school_name %><br />
      <%= f.text_field :school_name %>
    </div>
    <div class="field">
      <%= f.label :address1 %><br />
      <%= f.text_field :address1 %>
    </div>
    <div class="field">
      <%= f.label :address2 %><br />
      <%= f.text_field :address2 %>
    </div>
    <div class="field">
      <%= f.label :address3 %><br />
      <%= f.text_field :address3 %>
    </div>
    <div class="field">
      <%= f.label :town %><br />
      <%= f.text_field :town %>
    </div>
    <div class="field">
      <%= f.label :county %><br />
      <%= f.text_field :county %>
    </div>
    <div class="field">
      <%= f.label :post_code %><br />
      <%= f.text_field :post_code %>
    </div>
    <div class="field">
      <%= f.label :teacher_email %><br />
      <%= f.text_field :teacher_email %>
    </div>
    <div class="field">
      <%= f.label :group1_email %><br />
      <%= f.text_field :group1_email %>
    </div>
    <div class="field">
      <%= f.label :group2_email %><br />
      <%= f.text_field :group2_email %>
    </div>
    <div class="field">
      <%= f.label :invoice_to %><br />
      <%= f.text_field :invoice_to %>
    </div>
    <div class="field">
      <%#= f.hidden_field :book_id, :value => @book.id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>

  </fieldset>
<% end %>

app/views/ifgroups/_form.html.erb
<%= form_for(@ifgroup) do |f| %>
  <% if @ifgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ifgroup.errors.count, "error") %> prohibited this ifgroup from being saved:</h2>

      <ul>
      <% @ifgroup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p id="notice"><%= notice %></p>
  <fieldset>
    <legend>Enter Group details:</legend>
    <div>
      <%= f.label :group_name %><br />
      <%= f.text_field :group_name, size: 30 %>
    </div>
    <div>
      <%= f.label :password, 'Password' %><br />
      <%= f.password_field :password, size: 30 %>
    </div>
    <div>
      <%= f.label :password_confirmation, 'Confirm Password' %><br />
      <%= f.password_field :password_confirmation, size: 30 %>
    </div>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :school_name %><br />
      <%= f.text_field :school_name %>
    </div>
    <div class="field">
      <%= f.label :address1 %><br />
      <%= f.text_field :address1 %>
    </div>
    <div class="field">
      <%= f.label :address2 %><br />
      <%= f.text_field :address2 %>
    </div>
    <div class="field">
      <%= f.label :address3 %><br />
      <%= f.text_field :address3 %>
    </div>
    <div class="field">
      <%= f.label :town %><br />
      <%= f.text_field :town %>
    </div>
    <div class="field">
      <%= f.label :county %><br />
      <%= f.text_field :county %>
    </div>
    <div class="field">
      <%= f.label :post_code %><br />
      <%= f.text_field :post_code %>
    </div>
    <div class="field">
      <%= f.label :teacher_email %><br />
      <%= f.text_field :teacher_email %>
    </div>
    <div class="field">
      <%= f.label :group1_email %><br />
      <%= f.text_field :group1_email %>
    </div>
    <div class="field">
      <%= f.label :group2_email %><br />
      <%= f.text_field :group2_email %>
    </div>
    <div class="field">
      <%= f.label :invoice_to %><br />
      <%= f.text_field :invoice_to %>
    </div>
    <div class="field">
      <%#= f.hidden_field :book_id, :value => @book.id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>

  </fieldset>
<% end %>

app/views/ifgroups/_form.html.haml
= nested_form_for@ifgroup do |f|
  - if @ifgroup.errors.any?
    #error_explanation
      .h2
        = pluralize(@ifgroup.errors.count, "error")
        prohibited this book from being saved:

      %ul
        = @ifgroup.errors.full_messages.each do |msg|
          %li= msg


  %p
  %br/
  %fieldset
    %legend
      .fs_legend Enter Group details:
    %table
      %tr
        %td= f.label :group_name, 'Group Name:'
        %td=f.text_field :group_name, size: 30
      %tr
        %td= f.label :password, 'Password:'
        %td= f.password_field :password, size: 30
      %tr
        %td= f.label :password_confirmation, "Confirm Password:"
        %td= f.password_field :password_confirmation, size: 30
      %tr
        %td= f.label :title, "Title (Ms/Mr...):"
        %td= f.text_field :title, size: 30
      %tr
        %td= f.label :first_name, "First Name:"
        %td= f.text_field :first_name, size: 30
      %tr
        %td= f.label :last_name
        %td= f.text_field :last_name, size: 30
      %tr
        %td= f.label :school_name
        %td= f.text_field :school_name, size: 30
      %tr
        %td= f.label :address1
        %td= f.text_field :address1, size: 30
      %tr
        %td= f.label :address2
        %td= f.text_field :address2, size: 30
      %tr
        %td= f.label :address3
        %td= f.text_field :address3, size: 30
      %tr
        %td= f.label :town
        %td= f.text_field :town, size: 30
      %tr
        %td= f.label :county
        %td= f.text_field :county, size: 30
      %tr
        %td= f.label :post_code
        %td= f.text_field :post_code, size: 30
      %tr
        %td= f.label :teacher_email
        %td= f.text_field :teacher_email, size: 30
      %tr
        %td= f.label :group1_email
        %td= f.text_field :group1_email, size: 30
      %tr
        %td= f.label :group2_email
        %td= f.text_field :group2_email, size: 30
      %tr
        %td= f.label :invoice_to
        %td= f.text_field :invoice_to, size: 30

    = f.hidden_field :book_id, :value => @book.id


    %p
    %fieldset
      %legend
        .fs_legend_sub Add/Remove Members:
      = f.fields_for :members do |ffm|
        = ffm.label :name, 'Name: '
        = ffm.text_field :name
        = ffm.label :email, 'Email address: '
        = ffm.text_field :email, size: 30
        = ffm.link_to_remove "Remove this member?"
      %br/

      = f.link_to_add "Add another member", :members
    %br/
    %br/
    %p= f.submit "Submit"

app/views/ifgroups/edit.html.erb
<h1>Editing group: <%= @ifgroup.group_name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @ifgroup %> |
<%= link_to 'Back', ifgroups_path %>

app/views/ifgroups/index.html.erb
<h1>Listing ifgroups</h1>

<table>
  <tr>
    <th>Ifgroup Name</th>
    <th>Title</th>
    <th>First name</th>
    <th>Last name</th>
    <th>School name</th>
    <th>Address1</th>
    <th>Address2</th>
    <th>Address3</th>
    <th>Town</th>
    <th>County</th>
    <th>Post code</th>
    <th>Teacher email</th>
    <th>Group1 email</th>
    <th>Group2 email</th>
    <th>Invoice to</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ifgroups.each do |ifgroup| %>
  <tr>
    <td><%=	 ifgroup.group_name %></td>
    <td><%= ifgroup.title %></td>
    <td><%= ifgroup.first_name %></td>
    <td><%= ifgroup.last_name %></td>
    <td><%= ifgroup.school_name %></td>
    <td><%= ifgroup.address1 %></td>
    <td><%= ifgroup.address2 %></td>
    <td><%= ifgroup.address3 %></td>
    <td><%= ifgroup.town %></td>
    <td><%= ifgroup.county %></td>
    <td><%= ifgroup.post_code %></td>
    <td><%= ifgroup.teacher_email %></td>
    <td><%= ifgroup.group1_email %></td>
    <td><%= ifgroup.group2_email %></td>
    <td><%= ifgroup.invoice_to %></td>
    <td><%= link_to 'Show', ifgroup %></td>
    <td><%= link_to 'Edit', edit_ifgroup_path(ifgroup) %></td>
    <td><%= link_to 'Destroy', ifgroup, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ifgroup', new_ifgroup_path %>

app/views/ifgroups/new.html.erb
<section id="top_bar_content">
  Here is the..... Book Title <%= @book.title %>
</section>

<section id='body_content'>
  <h1>REGISTER HERE</h1>
  <p><strong>file: /home/eric/webs/ifbooks/app/views/ifgroups/new.html.erb</strong></p>
  <%= render 'form' %>

  <%= link_to 'Back', ifgroups_path %>
</section>


<section id='side_body_content'>



</section>

app/views/ifgroups/register.html.haml
#title_content
  %content#register_book_title
    = @book.title
%section#body_content
  %content#registration_form_holder
    .ifso-bigger-bolder Register your group here:
    %br/
    / <p><strong>this file is: /home/eric/webs/ifbooks/app/views/ifgroups/register.html.erb</strong></p>
    = render 'form'
    / <haml:loud> link_to 'Back', ifgroups_path </haml:loud>
%content#side_body_content
  = render 'refinery/pages/book_list'

app/views/ifgroups/show.html.haml
= @ifgroup.book.title
%p
  %b Title:
  = @ifgroup.title
%p
  %b First name:
  = @ifgroup.first_name
%p
  %b Last name:
  = @ifgroup.last_name
%p
  %b School name:
  = @ifgroup.school_name
%p
  %b Address1:
  = @ifgroup.address1
%p
  %b Address2:
  = @ifgroup.address2
%p
  %b Address3:
  = @ifgroup.address3
%p
  %b Town:
  = @ifgroup.town
%p
  %b County:
  = @ifgroup.county
%p
  %b Post code:
  = @ifgroup.post_code
%p
  %b Teacher email:
  = @ifgroup.teacher_email
%p
  %b Group1 email:
  = @ifgroup.group1_email
%p
  %b Group2 email:
  = @ifgroup.group2_email
%p
  %b Invoice to:
  = @ifgroup.invoice_to
%table.members_table
  %th
  %th
    Name
  %th
    Email
  - @ifgroup.members.each_with_index do |m, index|
    %tr
      %td
        %b
          = (index +1).ordinalize
          Member:
      %td
        -if m.name
          = m.name
        -else
          'Name not supplied'
      %td
        = m.email

= button_to 'Edit Group and Member Details', edit_ifgroup_path(@ifgroup), :method => :get
|
= button_to 'Back', '/'

= button_to 'Logout', group_logout_path, method: :delete

app/views/ifgroups/working_form.html.erb
<%= nested_form_for(@ifgroup) do |f| %>
  <% if @ifgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ifgroup.errors.count, "error") %> prohibited this ifgroup from being saved:</h2>

      <ul>
      <% @ifgroup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p id="notice"><%= notice %></p>
  <fieldset>
    <legend>Enter Group details:</legend>
    <div>
      <%= f.label :group_name %><br />
      <%= f.text_field :group_name, size: 30 %>
    </div>
    <div>
      <%= f.label :password, 'Password' %><br />
      <%= f.password_field :password, size: 30 %>
    </div>
    <div>
      <%= f.label :password_confirmation, 'Confirm Password' %><br />
      <%= f.password_field :password_confirmation, size: 30 %>
    </div>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :school_name %><br />
      <%= f.text_field :school_name %>
    </div>
    <div class="field">
      <%= f.label :address1 %><br />
      <%= f.text_field :address1 %>
    </div>
    <div class="field">
      <%= f.label :address2 %><br />
      <%= f.text_field :address2 %>
    </div>
    <div class="field">
      <%= f.label :address3 %><br />
      <%= f.text_field :address3 %>
    </div>
    <div class="field">
      <%= f.label :town %><br />
      <%= f.text_field :town %>
    </div>
    <div class="field">
      <%= f.label :county %><br />
      <%= f.text_field :county %>
    </div>
    <div class="field">
      <%= f.label :post_code %><br />
      <%= f.text_field :post_code %>
    </div>
    <div class="field">
      <%= f.label :teacher_email %><br />
      <%= f.text_field :teacher_email %>
    </div>
    <div class="field">
      <%= f.label :group1_email %><br />
      <%= f.text_field :group1_email %>
    </div>
    <div class="field">
      <%= f.label :group2_email %><br />
      <%= f.text_field :group2_email %>
    </div>
    <div class="field">
      <%= f.label :invoice_to %><br />
      <%= f.text_field :invoice_to %>
    </div>
    <div class="field">
      <%= f.hidden_field :book_id, :value => @book.id %>
    </div>
    <%= render 'members/members' %>
    <div class="actions">
      <%= f.submit %>
    </div>

  </fieldset>
<% end %>